import glob
import os

import pandas as pd

DATASET_DIR = "dataset"
OUTPUT_FILE = os.path.join(DATASET_DIR, "all_seasons.csv")

# 11-12.csv is generated by the current process_season_data.py logic and
# defines the feature set we want. Older/newer season files may carry extra
# columns (Rolling10, _all variants, Elo) from earlier pipeline versions —
# those are dropped so every season lines up on the same schema.
REFERENCE_FILE = os.path.join(DATASET_DIR, "11-12.csv")


def aggregate_seasons():
    reference_cols = pd.read_csv(REFERENCE_FILE, nrows=0).columns.tolist()

    season_files = sorted(
        f for f in glob.glob(os.path.join(DATASET_DIR, "*.csv"))
        if "all_seasons" not in os.path.basename(f)
    )

    frames = []
    for f in season_files:
        df = pd.read_csv(f, usecols=reference_cols)
        missing = [c for c in reference_cols if c not in df.columns]
        if missing:
            raise ValueError(f"{f} is missing expected columns: {missing}")
        df = df[reference_cols].copy()
        df["Season"] = os.path.splitext(os.path.basename(f))[0]
        frames.append(df)
        print(f"Loaded {f}: {df.shape}")

    all_seasons = pd.concat(frames, ignore_index=True)

    all_seasons["Date"] = pd.to_datetime(all_seasons["Date"])
    all_seasons = all_seasons.sort_values(["Date", "Time"]).reset_index(drop=True)

    print(f"\nAggregated shape: {all_seasons.shape}")
    return all_seasons


if __name__ == "__main__":
    all_seasons = aggregate_seasons()
    all_seasons.to_csv(OUTPUT_FILE, index=False)
    print(f"Saved aggregated dataset to {OUTPUT_FILE}")
